# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69d5e035f9a155dbb6b95e51dd16582a756ba0bd7db4f303f580d7731ab38f56bad2029c886ff94814d475a31d72e62c58b40539f00d7654bc71354bada124b6

test:
  secret_key_base: 0aee217e6498b1f8ff696e27b7e92b71cf541426f40db14ef76e34f53e583519d706149d1687dd314df30fc57b70343d267e74b8139b9f2e0e063bd0da120eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
